- debug:
    msg: Detect Graphics Cards

- name: Get a GPU
  get_gpu:
    audio: true
  register: this_pci

- name: Transform Vars
  block:
  - name: Append pci_string
    ansible.builtin.set_fact:
      vfio_pci_string: "{{ vfio_pci_string + ',' + this_pci.pci_string }}"
      cacheable: True
    when: vfio_pci_string != ""

  - name: Set pci_string (if empty)
    ansible.builtin.set_fact:
      vfio_pci_string: "{{ this_pci.pci_string }}"
      cacheable: True
    when: vfio_pci_string == ""

  - name: Make a global GPU variable (from this_pci)
    ansible.builtin.set_fact:
      gpu0: "{{ this_pci }}"

# Molecule
- name: dump test output
  debug:
    msg: "{{ this_pci }}"
    # msg: '{{ this_pci.pci_string }} {{ this_pci.gpu_type }} {{ this_pci.blacklist_driver }}'
  when: debug

- meta: end_play
  when: breakpoint

# from: https://www.heiko-sieger.info/blacklisting-graphics-driver/
