#!/bin/bash
# Works:
#https://www.reddit.com/r/archlinux/comments/7nmceg/kvmqemu_with_virtiogpu_virgl_support_enabled/

disk='ubuntu17.10.qcow2'

qemu-system-x86_64 \
    -show-cursor \
    -enable-kvm -M q35 -smp 6 -m 4G \
    -drive file=/var/lib/libvirt/images/$disk,if=virtio \
    -net nic,model=virtio \
    -net user,hostfwd=tcp::2222-:22 \
    -vga virtio \
    -display gtk,gl=on \
    -boot c
