---

- name: modules ignore_msrs
  ansible.builtin.lineinfile:
    path: /etc/initramfs-tools/modules
    regexp: '^options kvm ignore_msrs=1'
    line: 'options kvm ignore_msrs=1'
  when: enable_ignore_msrs
  become: true

- debug:
    msg: "--- Enabling ignore_msrs !!! ---"
  when: debug and enable_ignore_msrs