---
#https://forum.level1techs.com/t/linux-kernel-6-seems-to-be-incompatible-with-the-vfio-pci-module-needed-for-pci-passthrough/190039/37
#https://forum.zorin.com/t/zorin-os-17-doesnt-use-gpu-pass-for-kvm/32050/12

- name: Enable vfio-pci kernel module
  ansible.builtin.lineinfile:
    path: /etc/initramfs-tools/modules
    regexp: '^vfio-pci'
    line: vfio-pci
  become: true
  notify:
  - update initramfs Zorin OS
  