---
- name: Remove All devices pci.id from grub
  ansible.builtin.replace:
    path: /etc/default/grub
    before: 'GRUB_CMDLINE_LINUX'
    regexp: 'quiet splash"$'
    replace: 'quiet splash {{ ignore_msrs_kernel_cmdline }}"'
  become: true
  notify: ArchLinux Update grub
