---

- name: Todo - Use Autodetection instead!
  ansible.builtin.set_fact:
    existing_kernel_options: "quiet splash" # udev.log_priority=3

# Manjaro uses single quotes in etc/default/grub
# it also has trailing options like: "udev.log_priority=3"
# Uses clever quotes and regex $ to make idempotent!
- name: Enable iommu in grub kernel option
  ansible.builtin.replace:
    path: /etc/default/grub
    before: "GRUB_CMDLINE_LINUX"
    regexp: "'{{ existing_kernel_options }}" #'$"
    replace: "'intel_iommu=on {{ existing_kernel_options }}"
  become: true
  notify: ArchLinux Update grub

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: End it all
  ansible.builtin.meta: end_play