---
roles:
- UniInc.VFIO
- UniInc.OVMF
- UniInc.Enable-IOMMU
- UniInc.KVM-ignore_msrs
- UniInc.VFIO-PCI-Kernel-module
# - UniInc.VFIO-blacklist

# Functions:
- UniInc.Initramfs
- UniInc.Reboot
- UniInc.Update-Grub
